# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jonathan Clarke  
author:
  name: "Jonathan Clarke"
  email: hi@jonathanclarke.ie
description: Writing ugly code, creating beautiful businesses.

# Default image for Open Graph (social media previews)
# This will be used if a post doesn't specify its own image
image: https://www.jonathanclarke.ie/public/images/jc_logo.png


show_excerpts: true # set to true to show excerpts on the homepage
  
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.jonathanclarke.ie" # the base hostname & protocol for your site, e.g. http://example.com

minima:
  # social_links:
  #   - { platform: "github", user_url: "https://github.com/jonathanclarke" }
  # linkedin: jonathanclarkeireland
  # mastodon:
  #  - username: jonathanclarke
  #    instance: mastodon.ie

       
# twitter_username: sean_o_cleirigh
# github_username:  jonathanclarke
# mastodon_username: jonathanclarke

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  sort_field: 'date'
  sort_reverse: true


collections:
  fitness:
    output: true
    permalink: /fitness/:year/:month/:day/:title.html

feed:
  author: Jonathan Clarke
  collections:
    - fitness
    
############################################################

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
